### ISSUE TITLE
Kyverno Policy Report shows empty Resource Details list

### ISSUE THREAD

**Issue by mfilocha** [kyverno/policy-reporter-kyverno-plugin#29]
Kyverno Policy Report generated by policy-reporter-kyverno-plugin v1.6.2 (from policy-reporter helm chart 2.21.6) returns an empty Resource Details list, as shown below:

![image](https://github.com/kyverno/policy-reporter-kyverno-plugin/assets/12587791/8f8ac6d6-5dda-4a0f-a45f-d63b5c2b128b)

**Comment by fjogeleit** [comment]
Hey, thanks for reporting. I'll take a look on it.

**Comment by mfilocha** [comment]
I see this issue both on AKS and GKE 1.26 clusters.

**Comment by fjogeleit** [comment]
I am tagged a fixed version `1.6.3`, you can overwrite the tag via `kyvernoPlugin.image.tag` when its done, until I release a new helm chart version.

**Comment by mfilocha** [comment]
I did it already, just right the Docker build on GH has finished and pushed. It's working as expected. Thanks!
